### ISSUE TITLE
Both sitemap examples in the docs links don't work. 404

### ISSUE THREAD

**Issue by njarboe** [earthcubearchitecture-project418/p418Docs#13]
On this page:
https://github.com/earthcubearchitecture-project418/p418Docs

Sitemap examples http://149.165.168.129/sitemap.xml and http://149.165.168.129/xsedesitemap.xml

**Comment by fils** [comment]
@njarboe 
THANKS!..

I just removed them..  they were early testing at a site that only had IP addressing.   The better docs are at https://github.com/earthcubearchitecture-project418/p418Docs/blob/master/publishing.md or even better in https://github.com/earthcubearchitecture-project418/p418Vocabulary

I need to parse the main README down even more to point off to the better resources....
