### ISSUE TITLE
Tool for generating schema.org markup!!!

### ISSUE THREAD

**Issue by ashepherd** [earthcubearchitecture-project418/p418Docs#2]
https://schema.pythonanywhere.com/

Should we use?

- [ ] Test to see if usable for P418 publishing needs
- [ ] From publishing docs, give links to specific schema.org types e.g. [create a ServiceChannel](https://schema.pythonanywhere.com/ServiceChannel)

**Comment by fils** [comment]
Also worth looking at and adding to docs (publish.md)

https://www.schemaapp.com/tips/structured-data-testing-tool-error-guide/
